# Generated by Django 5.2 on 2025-04-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_message_user_chatsession_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession'),
        ),
    ]
